<a href="https://colab.research.google.com/github/jongkwangyun/quant/blob/main/%EB%8F%99%EC%A0%81%EC%9E%90%EC%82%B0%EB%B0%B0%EB%B6%84_DAA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 첫 설치 이후 설치 안함
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.10/dist-packages (0.2.28)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.5.3)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.23.5)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.31.0)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.10/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (4.9.3)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2023.3)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.3.8)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (4.11.2)
Requirement already satisfied: html5lib>=1.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (2023.7.22)

In [2]:
# 첫 설치 이후 설치 안함
!pip install pandas_market_calendars

Collecting pandas_market_calendars
  Downloading pandas_market_calendars-4.2.1-py3-none-any.whl (103 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.8/103.8 kB 1.7 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.1 in /usr/local/lib/python3.10/dist-packages (from pandas_market_calendars) (1.5.3)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from pandas_market_calendars) (2023.3)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from pandas_market_calendars) (2.8.2)
Collecting exchange-calendars>=3.3 (from pandas_market_calendars)
  Downloading exchange_calendars-4.2.8-py3-none-any.whl (191 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 191.4/191.4 kB 12.5 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from exchange-calendars>=3.3->pandas_market_calendars) (1.23.5)
Collecting pyluach (from exchange-calendars>=3.3->pandas_market_calendars)
  Downloading pyluach-2.2.0-py3-none-any.whl (25 kB)
Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from exchange-calendars>=3.3->pandas_market_calendars) (0.12.0)
Collecting korean-lunar-calendar (from exchange-calendars>=3.3->pandas_market_calendars)
  Downloading korean_lunar_calendar-0.3.1-py3-none-any.whl (9.0 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil->pandas_market_calendars) (1.16.0)
Installing collected packages: korean-lunar-calendar, pyluach, exchange-calendars, pandas_market_calendars
Successfully installed exchange-calendars-4.2.8 korean-lunar-calendar-0.3.1 pandas_market_calendars-4.2.1 pyluach-2.2.0

In [3]:
import yfinance as yf
import pandas as pd
# import exchange_calendars as ecals
from datetime import datetime, timedelta
from IPython.display import display, Markdown
import csv

# display에서 소수점 4자리까지 표현
pd.options.display.float_format = '{:.4f}'.format

# display시 DataFrame 모든 열 표시
pd.set_option('display.max_columns', None)

# 데이터 가져올 기간을 지정합니다. (오늘로부터 12개월 전)
end_date = datetime.today().date()
start_date = end_date - timedelta(days=375)
today = datetime.today().date()

'''
# 1년 전 개장일 구하기
us_market_code = "XNYS"
us_calendar = ecals.get_calendar(us_market_code)

# 각 날짜 변수에 저장
today = datetime.today().date()
today_workday = pd.Timestamp(us_calendar.previous_open(today - timedelta(days=0)).date())
month_01_ago_workday = pd.Timestamp(us_calendar.previous_open(today - timedelta(days=30)).date())
month_03_ago_workday = pd.Timestamp(us_calendar.previous_open(today - timedelta(days=91)).date())
month_06_ago_workday = pd.Timestamp(us_calendar.previous_open(today - timedelta(days=182)).date())
month_12_ago_workday = pd.Timestamp(us_calendar.previous_open(today - timedelta(days=365)).date())
'''

# 전략에 사용할 ETF 명 리스트에 담기
canary_etf = ['VWO', 'BND']
aggressive_etf = ['SPY', 'IWM', 'QQQ', 'VGK', 'EWJ', 'VWO', 'VNQ', 'GSG', 'GLD', 'TLT', 'HYG', 'LQD']
defensive_etf = ['SHY', 'IEF', 'LQD']

# 자산군 리스트 더하기, 중복 제거
etf_order = list(set(canary_etf + aggressive_etf + defensive_etf))

# ETF 가격 추출
df_etf = yf.download(etf_order, start=start_date, end=end_date)['Adj Close']\
.sort_index(ascending=False)[etf_order].rename_axis(None, axis=0)

display(df_etf)

[*********************100%%**********************]  15 of 15 completed

,BND,IWM,IEF,EWJ,TLT,HYG,VNQ,VGK,GSG,GLD,SPY,VWO,QQQ,LQD,SHY
2023-08-22,70.6200,183.8300,93.0600,59.6600,93.2300,74.1100,79.9300,59.9200,21.1500,176.1000,438.1500,39.8400,363.3800,103.8000,80.8800
2023-08-21,70.5300,184.3800,93.0200,59.3700,92.5200,74.0700,79.7000,60.1400,21.2100,175.8100,439.3400,39.9100,363.9000,103.4800,80.9200
2023-08-18,70.8700,184.6500,93.6000,59.3200,93.7700,74.0900,80.4400,59.8000,21.2800,175.3300,436.5000,39.8200,358.1300,104.1000,81.0100
2023-08-17,70.7200,183.6500,93.3200,59.1700,93.4400,74.0400,80.1900,59.9000,21.0500,175.3000,436.2900,40.0700,358.5800,103.7100,80.9800
2023-08-16,70.7900,185.8400,93.4400,59.4200,93.8400,74.3500,80.8400,60.4200,20.9200,175.5700,439.6400,39.9400,362.5400,103.9900,80.8900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-19,73.3640,191.5199,99.8816,55.1257,109.7055,72.6273,95.0448,52.5108,22.3800,162.7200,415.3573,40.0994,320.5744,107.3997,80.5327
2022-08-18,73.8304,195.7213,100.7491,56.0968,111.5009,73.3729,96.0571,53.2366,22.3600,163.9200,421.0149,40.5529,326.9489,108.6893,80.5913
2022-08-17,73.6944,194.4323,100.5541,56.2950,111.3359,73.2596,96.6970,53.4979,22.0200,164.3500,419.7948,40.8134,326.1645,108.4102,80.4742
2022-08-16,74.1317,197.7580,101.2364,56.4733,112.5102,74.0241,97.2795,54.0495,21.8600,165.4200,422.7958,40.9099,329.9277,109.4399,80.5425
2022-08-15,74.2289,197.8367,101.3533,56.7409,112.0444,74.3734,97.5374,53.9721,22.1200,165.7100,421.9693,40.8906,330.7022,109.8634,80.6108

In [4]:
# csv 경로 설정
output_path =  '/content/drive/MyDrive/DynamicAssetAllocation/'

# 오늘 날짜를 가져와서 파일명에 추가
today_date = datetime.now().strftime('%y%m%d')
filename = f'{today_date} DAA.xlsx'

# 오늘 날짜 string에 저장
str_today = today.strftime('### %Y-%m-%d ')

# 월평균영업일수. average Monthly Business Day
MBD = 21

# 인덱스 만들기
df_momentum_index = ['today/' + str(df_etf.index[0].date()), '1mo_ago/' + str(df_etf.index[MBD].date()), \
                     '3mo_ago/' + str(df_etf.index[MBD*3].date()), '6mo_ago/' + str(df_etf.index[MBD*6].date()), \
                     '12mo_ago/' + str(df_etf.index[MBD*12].date())]


## DataFrame 만들기: 1-3-6-12 개월 etf 가격
price_today = df_etf.iloc[0:1]
price_1mo = df_etf.shift(-MBD).iloc[0:1]
price_3mo = df_etf.shift(-MBD*3).iloc[0:1]
price_6mo = df_etf.shift(-MBD*6).iloc[0:1]
price_12mo = df_etf.shift(-MBD*12).iloc[0:1]

df_price = pd.concat([price_today, price_1mo, price_3mo, price_6mo, price_12mo])
df_price.index = df_momentum_index

str_etf_price = str_today + "### ETF 현재-1-3-6-12 개월 가격"
display(Markdown(str_etf_price))
display(df_price)

# csv에 제목 및 DataFrame 추가. 드라이브 마운트 후 해야함
with open(output_path + filename, 'w') as f:
  f.write(f'{str_etf_price}\n')
  df_price.to_csv(f, index=True)

### 2023-08-23 ### ETF 현재-1-3-6-12 개월 가격

,BND,IWM,IEF,EWJ,TLT,HYG,VNQ,VGK,GSG,GLD,SPY,VWO,QQQ,LQD,SHY
today/2023-08-22,70.6200,183.8300,93.0600,59.6600,93.2300,74.1100,79.9300,59.9200,21.1500,176.1000,438.1500,39.8400,363.3800,103.8000,80.8800
1mo_ago/2023-07-24,72.3068,194.9400,95.9668,62.5000,101.0814,74.8832,86.8900,63.1000,21.3000,181.4000,454.2000,41.8900,376.2300,107.4710,80.8282
3mo_ago/2023-05-22,72.0879,177.7677,96.7408,60.8114,99.9262,73.4270,79.9868,61.7978,19.2400,183.2100,417.2401,39.9327,337.1775,105.5203,81.1330
6mo_ago/2023-02-21,70.8423,186.2252,94.0595,55.9349,98.8336,71.2519,85.5468,59.1785,20.3800,170.6200,396.1013,40.0131,293.1734,103.4395,79.8858
12mo_ago/2022-08-19,73.3640,191.5199,99.8816,55.1257,109.7055,72.6273,95.0448,52.5108,22.3800,162.7200,415.3573,40.0994,320.5744,107.3997,80.5327

In [5]:
## DataFrame 만들기: 수익률
ror_1mo = df_etf.pct_change(-MBD).iloc[0:1]*100    # 1개월 수익률
ror_3mo = df_etf.pct_change(-MBD*3).iloc[0:1]*100    # 3개월 수익률
ror_6mo = df_etf.pct_change(-MBD*6).iloc[0:1]*100   # 6개월 수익률
ror_12mo = df_etf.pct_change(-MBD*12).iloc[0:1]*100  # 12개월 수익률

df_etf_ror = pd.concat([ror_1mo, ror_3mo, ror_6mo, ror_12mo])
df_etf_ror.index = df_momentum_index[1:]

str_etf_ror = str_today + "### ETF 1-3-6-12 개월 수익률"
display(Markdown(str_etf_ror))
display(df_etf_ror)

# csv에 제목 및 DataFrame 추가
with open(output_path + filename, 'a') as f:
  f.write('\n')
  f.write(f'{str_etf_ror}\n')
  df_etf_ror.to_csv(f, index=True)

### 2023-08-23 ### ETF 1-3-6-12 개월 수익률

,BND,IWM,IEF,EWJ,TLT,HYG,VNQ,VGK,GSG,GLD,SPY,VWO,QQQ,LQD,SHY
1mo_ago/2023-07-24,-2.3328,-5.6992,-3.0290,-4.5440,-7.7674,-1.0326,-8.0101,-5.0396,-0.7042,-2.9217,-3.5337,-4.8938,-3.4155,-3.4158,0.0641
3mo_ago/2023-05-22,-2.0363,3.4102,-3.8048,-1.8934,-6.7012,0.9302,-0.0710,-3.0386,9.9272,-3.8808,5.0115,-0.2321,7.7711,-1.6303,-0.3119
6mo_ago/2023-02-21,-0.3138,-1.2862,-1.0626,6.6596,-5.6698,4.0113,-6.5658,1.2530,3.7782,3.2118,10.6156,-0.4327,23.9471,0.3485,1.2445
12mo_ago/2022-08-19,-3.7402,-4.0152,-6.8297,8.2255,-15.0179,2.0415,-15.9028,14.1099,-5.4960,8.2227,5.4875,-0.6468,13.3528,-3.3517,0.4312

In [6]:
## DataFrame 만들기: 수익률 가중치
df_etf_ror_weight = df_etf_ror.copy()
df_etf_ror_weight.iloc[0] *= 12
df_etf_ror_weight.iloc[1] *= 4
df_etf_ror_weight.iloc[2] *= 2

str_etf_ror_weight = str_today + "### ETF 1-3-6-12 개월 가중치 적용"
display(Markdown(str_etf_ror_weight))
display(df_etf_ror_weight)

# csv에 제목 및 DataFrame 추가
with open(output_path + filename, 'a') as f:
  f.write('\n')
  f.write(f'{str_etf_ror_weight}\n')
  df_etf_ror_weight.to_csv(f, index=True)

### 2023-08-23 ### ETF 1-3-6-12 개월 가중치 적용

,BND,IWM,IEF,EWJ,TLT,HYG,VNQ,VGK,GSG,GLD,SPY,VWO,QQQ,LQD,SHY
1mo_ago/2023-07-24,-27.9938,-68.3903,-36.3477,-54.5280,-93.2088,-12.3910,-96.1215,-60.4754,-8.4507,-35.0606,-42.4043,-58.7252,-40.9856,-40.9900,0.7689
3mo_ago/2023-05-22,-8.1453,13.6410,-15.2192,-7.5734,-26.8046,3.7209,-0.2840,-12.1543,39.7089,-15.5232,20.0459,-0.9285,31.0845,-6.5212,-1.2475
6mo_ago/2023-02-21,-0.6276,-2.5724,-2.1252,13.3192,-11.3395,8.0225,-13.1316,2.5060,7.5564,6.4236,21.2313,-0.8655,47.8943,0.6970,2.4890
12mo_ago/2022-08-19,-3.7402,-4.0152,-6.8297,8.2255,-15.0179,2.0415,-15.9028,14.1099,-5.4960,8.2227,5.4875,-0.6468,13.3528,-3.3517,0.4312

In [7]:
df_etf_momentum_score = (12 * ror_1mo) + (4 * ror_3mo) + (2 * ror_6mo) + (ror_12mo)
df_etf_momentum_score.index = ['momentum_score']

str_etf_momentum_score = str_today + "### ETF 별 1-3-6-12 개월 Momentum Score"
display(Markdown(str_etf_momentum_score))
display(df_etf_momentum_score)

# csv에 제목 및 DataFrame 추가
with open(output_path + filename, 'a') as f:
  f.write('\n')
  f.write(f'{str_etf_momentum_score}\n')
  df_etf_momentum_score.to_csv(f, index=True)

### 2023-08-23 ### ETF 별 1-3-6-12 개월 Momentum Score

,BND,IWM,IEF,EWJ,TLT,HYG,VNQ,VGK,GSG,GLD,SPY,VWO,QQQ,LQD,SHY
momentum_score,-40.5068,-61.3369,-60.5220,-40.5567,-146.3708,1.3940,-125.4399,-56.0139,33.3187,-35.9374,4.3603,-61.1660,51.3460,-50.1659,2.4416

In [14]:
# 카나리아 자산군 0 미만 개수 세기
canary_etf_negative_count = (df_etf_momentum_score[canary_etf] < 0).sum().sum()
aggressive_portion = 0

if canary_etf_negative_count == 0:
  aggressive_portion = 100
elif canary_etf_negative_count == 1:
  aggressive_portion = 50
else:
  aggressive_portion = 0


## 종목 출력하기
aggressive_etf_list_text = ''
defensive_etf_list_text = ''

# 카나리아 자산군 중 모멘텀스코어 0 미만 개수: 0
if canary_etf_negative_count <= 1:
  momentum_scores_aggressive_top_6 = df_etf_momentum_score[aggressive_etf].transpose().nlargest(6, 'momentum_score').transpose()

  str_aggressive_momentum_score = str_today + "### 공격자산 Momentum Score"
  display(Markdown(str_aggressive_momentum_score))
  display(momentum_scores_aggressive_top_6)
  etf_columns = momentum_scores_aggressive_top_6.columns
  aggressive_etf_list_text = ' '.join([str(asset) for asset in etf_columns])

# 0 미만 카나리아 자산군 개수: 1 or 2
if canary_etf_negative_count >= 1:
  momentum_scores_defensive_top_1 = df_etf_momentum_score[defensive_etf].transpose().nlargest(1, 'momentum_score').transpose()

  str_defensive_momentum_score = str_today + "### 안전자산 Momentum Score"
  display(Markdown(str_defensive_momentum_score))
  display(momentum_scores_defensive_top_1)
  etf_columns = momentum_scores_defensive_top_1.columns
  defensive_etf_list_text = ' '.join([str(asset) for asset in etf_columns])


str_canary_text = "## 카나리아 자산군 중 모멘텀스코어 0 미만 개수: " + str(canary_etf_negative_count)
str_aggressive_text = "## 공격자산 비율: " + str(aggressive_portion) + " %"
display(Markdown(str_today[1:]))
display(Markdown(str_canary_text))
display(Markdown(str_aggressive_text))

str_aggressive_etf_list = '## 추천 공격자산: '
if canary_etf_negative_count <= 1:
  str_aggressive_etf_list += aggressive_etf_list_text

str_defensive_etf_list = '## 추천 안전자산: '
if canary_etf_negative_count >= 1:
  str_defensive_etf_list += defensive_etf_list_text

display(Markdown(str_aggressive_etf_list))
display(Markdown(str_defensive_etf_list))

# csv에 자산 투자 조언 추가
with open(output_path + filename, 'a') as f:
  f.write('\n')
  f.write(f'{str_today[1:]}\n')
  f.write(f'{str_canary_text}\n')
  f.write(f'{str_aggressive_text}\n')
  f.write(f'{str_aggressive_etf_list}\n')
  f.write(f'{str_defensive_etf_list}')

### 2023-08-23 ### 안전자산 Momentum Score

                  SHY
momentum_score 2.4416

## 2023-08-23

## 카나리아 자산군 중 모멘텀스코어 0 미만 개수: 2

## 공격자산 비율: 0 %

## 추천 공격자산:

## 추천 안전자산: SHY