<a href="https://colab.research.google.com/github/jongkwangyun/quant/blob/main/%EB%8F%99%EC%A0%81%EC%9E%90%EC%82%B0%EB%B0%B0%EB%B6%84_BAA_med.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [81]:
# 첫 설치 이후 설치 안함
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.10/dist-packages (0.2.28)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.5.3)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.23.5)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.31.0)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.10/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (4.9.3)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2023.3)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.3.8)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (4.11.2)
Requirement already satisfied: html5lib>=1.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (2023.7.22)

In [82]:
# 첫 설치 이후 설치 안함
!pip install pandas_market_calendars

Requirement already satisfied: pandas_market_calendars in /usr/local/lib/python3.10/dist-packages (4.2.1)
Requirement already satisfied: pandas>=1.1 in /usr/local/lib/python3.10/dist-packages (from pandas_market_calendars) (1.5.3)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from pandas_market_calendars) (2023.3)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from pandas_market_calendars) (2.8.2)
Requirement already satisfied: exchange-calendars>=3.3 in /usr/local/lib/python3.10/dist-packages (from pandas_market_calendars) (4.2.8)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from exchange-calendars>=3.3->pandas_market_calendars) (1.23.5)
Requirement already satisfied: pyluach in /usr/local/lib/python3.10/dist-packages (from exchange-calendars>=3.3->pandas_market_calendars) (2.2.0)
Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from exchange-calendars>=3.3->pandas_market_calendars) (0.12.0)
Requirement already satisfied: korean-lunar-calendar in /usr/local/lib/python3.10/dist-packages (from exchange-calendars>=3.3->pandas_market_calendars) (0.3.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil->pandas_market_calendars) (1.16.0)

In [83]:
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta
from IPython.display import display, Markdown
import csv

# display에서 소수점 4자리까지 표현
pd.options.display.float_format = '{:.4f}'.format

# display시 DataFrame 모든 열 표시
pd.set_option('display.max_columns', None)

# 데이터 가져올 기간을 지정합니다. (오늘로부터 12개월 전)
today = datetime.today().date()
start_date = today - timedelta(days=375)

# 전략명
str_strategy = 'BAA_med '

# 전략에 사용할 ETF 명 리스트에 담기
canary_etf = ['SPY', 'VEA', 'VWO', 'BND']
aggressive_etf = ['SPY', 'QQQ', 'IWM', 'VGK', 'EWJ', 'EEM', 'IYR', 'GSG', 'GLD', 'HYG', 'LQD', 'TLT']
defensive_etf = ['BIL', 'IEF', 'TLT', 'LQD', 'TIP', 'BND', 'DBC']

# 자산군 리스트 더하기, 중복 제거
etf_order = list(set(canary_etf + aggressive_etf + defensive_etf))

# ETF 가격 추출
df_etf = yf.download(etf_order, start=start_date, end=today)['Adj Close']\
.sort_index(ascending=False)[etf_order].rename_axis(None, axis=0)

display(df_etf)

[*********************100%%**********************]  19 of 19 completed

,VEA,IEF,TLT,SPY,EWJ,QQQ,VGK,DBC,VWO,BND,TIP,IWM,HYG,GLD,BIL,EEM,GSG,IYR,LQD
2023-08-24,44.5800,93.7200,94.9100,436.8900,59.6600,361.2200,59.5800,24.1700,40.2600,71.0900,105.4500,183.2200,74.3000,177.8500,91.7500,38.8700,21.1500,83.6400,104.9000
2023-08-23,45.1500,94.0700,95.5400,443.0300,60.4500,369.1100,60.4200,24.1500,40.4300,71.2600,105.9300,185.7900,74.7100,177.8900,91.7200,39.0200,21.1200,84.0000,105.2600
2023-08-22,44.6700,93.0600,93.2300,438.1500,59.6600,363.3800,59.9200,24.1000,39.8400,70.6200,104.9800,183.8300,74.1100,176.1000,91.7000,38.4100,21.1500,82.6700,103.8000
2023-08-21,44.7700,93.0200,92.5200,439.3400,59.3700,363.9000,60.1400,24.0900,39.9100,70.5300,104.8000,184.3800,74.0700,175.8100,91.6900,38.4900,21.2100,82.4000,103.4800
2023-08-18,44.6300,93.6000,93.7700,436.5000,59.3200,358.1300,59.8000,24.1500,39.8200,70.8700,105.0800,184.6500,74.0900,175.3300,91.6800,38.4000,21.2800,83.1300,104.1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-19,41.1656,99.8816,109.7055,415.3573,55.1257,320.5744,52.5108,25.8042,40.0994,73.3640,111.6793,191.5199,72.6273,162.7200,88.0716,38.9955,22.3800,97.7019,107.3997
2022-08-18,41.7882,100.7491,111.5009,421.0149,56.0968,326.9490,53.2366,25.8141,40.5529,73.8305,111.8728,195.7212,73.3729,163.9200,88.0716,39.5330,22.3600,98.6046,108.6893
2022-08-17,41.9244,100.5541,111.3359,419.7949,56.2950,326.1646,53.4979,25.4265,40.8134,73.6944,111.3020,194.4323,73.2596,164.3500,88.0331,39.7578,22.0200,99.3714,108.4102
2022-08-16,42.2843,101.2364,112.5102,422.7959,56.4733,329.9277,54.0495,25.3271,40.9099,74.1317,111.6406,197.7580,74.0241,165.4200,88.0331,39.9240,21.8600,99.7887,109.4399
2022-08-15,42.2454,101.3534,112.0444,421.9693,56.7409,330.7022,53.9721,25.6153,40.8906,74.2289,111.6116,197.8367,74.3734,165.7100,88.0234,39.9337,22.1200,100.1576,109.8634

In [91]:
# csv 경로 설정
output_path =  '/content/drive/MyDrive/DynamicAssetAllocation/'

# 오늘 날짜를 가져와서 파일명에 추가
today_date = datetime.now().strftime('%y%m%d')
filename = f'{today_date} BAA_med.xlsx'

# 오늘 날짜 string에 저장
str_today = today.strftime('### %Y-%m-%d ')

# 월평균영업일수. average Monthly Business Day
MBD = 21

# 인덱스 만들기
df_momentum_index = ['today/' + str(df_etf.index[0].date()), '1mo_ago/' + str(df_etf.index[MBD].date()), \
                     '3mo_ago/' + str(df_etf.index[MBD*3].date()), '6mo_ago/' + str(df_etf.index[MBD*6].date()), \
                     '12mo_ago/' + str(df_etf.index[MBD*12].date())]


## DataFrame 만들기: 1-3-6-12 개월 etf 가격
price_today = df_etf.iloc[0:1]
price_1mo = df_etf.shift(-MBD).iloc[0:1]
price_3mo = df_etf.shift(-MBD*3).iloc[0:1]
price_6mo = df_etf.shift(-MBD*6).iloc[0:1]
price_12mo = df_etf.shift(-MBD*12).iloc[0:1]

df_price = pd.concat([price_today, price_1mo, price_3mo, price_6mo, price_12mo])
df_price.index = df_momentum_index

str_etf_price = str_today + str_strategy + "### ETF 현재-1-3-6-12 개월 가격"
display(Markdown(str_etf_price))
display(df_price)

# csv에 제목 및 DataFrame 추가. 드라이브 마운트 후 해야함
# with open(output_path + filename, 'w') as f:
#   f.write(f'{str_etf_price}\n')
#   df_price.to_csv(f, index=True)

### 2023-08-25 BAA_med ### ETF 현재-1-3-6-12 개월 가격

,VEA,IEF,TLT,SPY,EWJ,QQQ,VGK,DBC,VWO,BND,TIP,IWM,HYG,GLD,BIL,EEM,GSG,IYR,LQD
today/2023-08-24,44.5800,93.7200,94.9100,436.8900,59.6600,361.2200,59.5800,24.1700,40.2600,71.0900,105.4500,183.2200,74.3000,177.8500,91.7500,38.8700,21.1500,83.6400,104.9000
1mo_ago/2023-07-26,47.4400,96.1164,100.9916,455.5100,62.8300,377.5200,63.3400,24.4900,42.4700,72.4664,107.2883,196.4600,75.1320,183.3000,91.3363,41.4500,21.2500,89.6900,107.7999
3mo_ago/2023-05-24,44.7268,96.6515,99.7179,409.5686,59.3018,331.1957,59.9406,22.8300,39.0574,71.9391,107.0516,175.0552,72.5304,181.9500,90.5284,38.1015,19.4600,80.1317,105.3223
6mo_ago/2023-02-23,44.1249,94.5921,100.7140,397.6595,56.0740,295.9553,59.1883,23.7500,39.9833,71.2561,105.5593,188.0633,72.4263,169.5700,89.5847,38.8754,20.1700,87.5755,104.5473
12mo_ago/2022-08-23,40.5820,99.1994,108.7350,405.7246,54.6896,311.8765,51.3398,26.4602,40.0704,73.0044,111.6503,187.8794,71.9855,162.7700,88.0619,38.8587,23.0300,94.3921,106.7934

In [85]:
## DataFrame 만들기: 수익률
ror_1mo = df_etf.pct_change(-MBD).iloc[0:1]*100    # 1개월 수익률
ror_3mo = df_etf.pct_change(-MBD*3).iloc[0:1]*100    # 3개월 수익률
ror_6mo = df_etf.pct_change(-MBD*6).iloc[0:1]*100   # 6개월 수익률
ror_12mo = df_etf.pct_change(-MBD*12).iloc[0:1]*100  # 12개월 수익률

df_etf_ror = pd.concat([ror_1mo, ror_3mo, ror_6mo, ror_12mo])
df_etf_ror.index = df_momentum_index[1:]

str_etf_ror = str_today + str_strategy + "### ETF 1-3-6-12 개월 수익률"
display(Markdown(str_etf_ror))
display(df_etf_ror)

# csv에 제목 및 DataFrame 추가
with open(output_path + filename, 'a') as f:
  f.write('\n')
  f.write(f'{str_etf_ror}\n')
  df_etf_ror.to_csv(f, index=True)

### 2023-08-25 BAA_med ### ETF 1-3-6-12 개월 수익률

,VEA,IEF,TLT,SPY,EWJ,QQQ,VGK,DBC,VWO,BND,TIP,IWM,HYG,GLD,BIL,EEM,GSG,IYR,LQD
1mo_ago/2023-07-26,-6.0287,-2.4933,-6.0219,-4.0877,-5.0454,-4.3176,-5.9362,-1.3067,-5.2037,-1.8993,-1.7134,-6.7393,-1.1074,-2.9733,0.4529,-6.2244,-0.4706,-6.7455,-2.6901
3mo_ago/2023-05-24,-0.3281,-3.0330,-4.8215,6.6708,0.6041,9.0654,-0.6016,5.8695,3.0789,-1.1803,-1.4961,4.6641,2.4397,-2.2534,1.3494,2.0170,8.6845,4.3781,-0.4009
6mo_ago/2023-02-23,1.0315,-0.9220,-5.7629,9.8653,6.3951,22.0522,0.6618,1.7684,0.6919,-0.2330,-0.1035,-2.5754,2.5870,4.8829,2.4171,-0.0140,4.8587,-4.4939,0.3374
12mo_ago/2022-08-23,9.8517,-5.5236,-12.7144,7.6814,9.0883,15.8215,16.0503,-8.6554,0.4731,-2.6223,-5.5533,-2.4800,3.2153,9.2646,4.1880,0.0292,-8.1633,-11.3909,-1.7730

In [86]:
## DataFrame 만들기: 수익률 가중치
df_etf_ror_weight = df_etf_ror.copy()
df_etf_ror_weight.iloc[0] *= 12
df_etf_ror_weight.iloc[1] *= 4
df_etf_ror_weight.iloc[2] *= 2

str_etf_ror_weight = str_today + str_strategy + "### ETF 1-3-6-12 개월 가중치 적용"
display(Markdown(str_etf_ror_weight))
display(df_etf_ror_weight)

# csv에 제목 및 DataFrame 추가
with open(output_path + filename, 'a') as f:
  f.write('\n')
  f.write(f'{str_etf_ror_weight}\n')
  df_etf_ror_weight.to_csv(f, index=True)

### 2023-08-25 BAA_med ### ETF 1-3-6-12 개월 가중치 적용

,VEA,IEF,TLT,SPY,EWJ,QQQ,VGK,DBC,VWO,BND,TIP,IWM,HYG,GLD,BIL,EEM,GSG,IYR,LQD
1mo_ago/2023-07-26,-72.3439,-29.9191,-72.2631,-49.0527,-60.5444,-51.8118,-71.2346,-15.6799,-62.4442,-22.7919,-20.5609,-80.8715,-13.2892,-35.6792,5.4352,-74.6925,-5.6471,-80.9455,-32.2809
3mo_ago/2023-05-24,-1.3125,-12.1321,-19.2860,26.6831,2.4163,36.2617,-2.4064,23.4779,12.3157,-4.7213,-5.9845,18.6565,9.7590,-9.0134,5.3977,8.0679,34.7379,17.5126,-1.6037
6mo_ago/2023-02-23,2.0629,-1.8440,-11.5257,19.7307,12.7903,44.1045,1.3236,3.5368,1.3839,-0.4661,-0.2071,-5.1508,5.1741,9.7659,4.8342,-0.0280,9.7174,-8.9877,0.6748
12mo_ago/2022-08-23,9.8517,-5.5236,-12.7144,7.6814,9.0883,15.8215,16.0503,-8.6554,0.4731,-2.6223,-5.5533,-2.4800,3.2153,9.2646,4.1880,0.0292,-8.1633,-11.3909,-1.7730

In [87]:
df_etf_momentum_score = (12 * ror_1mo) + (4 * ror_3mo) + (2 * ror_6mo) + (ror_12mo)
df_etf_momentum_score.index = ['momentum_score']

str_etf_momentum_score = str_today + str_strategy + "### ETF 별 1-3-6-12 개월 Momentum Score"
display(Markdown(str_etf_momentum_score))
display(df_etf_momentum_score)

# csv에 제목 및 DataFrame 추가
with open(output_path + filename, 'a') as f:
  f.write('\n')
  f.write(f'{str_etf_momentum_score}\n')
  df_etf_momentum_score.to_csv(f, index=True)

### 2023-08-25 BAA_med ### ETF 별 1-3-6-12 개월 Momentum Score

,VEA,IEF,TLT,SPY,EWJ,QQQ,VGK,DBC,VWO,BND,TIP,IWM,HYG,GLD,BIL,EEM,GSG,IYR,LQD
momentum_score,-61.7419,-49.4188,-115.7892,5.0425,-36.2494,44.3759,-56.2669,2.6795,-48.2715,-30.6016,-32.3059,-69.8457,4.8591,-25.6622,19.8552,-66.6234,30.6450,-83.8116,-34.9828

In [88]:
# 12개월 이동평균 생성 및 저장
etf_12mo_ma = df_etf.rolling(window=252).mean().loc[df_etf.index[251]]  # 252 개의 영업일은 대략 12개월
df_etf_12mo_ma = pd.DataFrame([etf_12mo_ma], columns=etf_order, index=['12mo_moving_average'])

# 12개월 이동평균 수익률 생성 및 저장
df_etf_12mo_ror = (df_etf.iloc[0]/df_etf_12mo_ma - 1)*100
df_etf_12mo_ror.index = ['12mo_ma_ror(%)']

df_etf_12mo_ma = pd.concat([df_etf_12mo_ma, df_etf_12mo_ror])

str_etf_12mo_ma = str_today + str_strategy + "### ETF 별 12 개월의 Moving Average 및 수익률"
display(Markdown(str_etf_12mo_ma))
display(df_etf_12mo_ma)

# csv에 제목 및 DataFrame 추가
with open(output_path + filename, 'a') as f:
  f.write('\n')
  f.write(f'{str_etf_12mo_ma}\n')
  df_etf_12mo_ma.to_csv(f, index=True)

### 2023-08-25 BAA_med ### ETF 별 12 개월의 Moving Average 및 수익률

,VEA,IEF,TLT,SPY,EWJ,QQQ,VGK,DBC,VWO,BND,TIP,IWM,HYG,GLD,BIL,EEM,GSG,IYR,LQD
12mo_moving_average,43.0339,95.9418,101.3168,403.9233,56.5193,311.2490,56.8099,24.1260,39.5309,71.6053,106.4921,180.5514,72.4175,172.7161,89.6777,38.3979,20.6944,85.1519,104.9623
12mo_ma_ror(%),3.5927,-2.3157,-6.3235,8.1616,5.5568,16.0550,4.8761,0.1822,1.8445,-0.7197,-0.9786,1.4781,2.5995,2.9724,2.3108,1.2296,2.2017,-1.7755,-0.0593

In [89]:
# 카나리아 자산군 0 미만 개수 세기
canary_etf_negative_count = (df_etf_momentum_score[canary_etf] < 0).sum().sum()
aggressive_portion = 0

if canary_etf_negative_count == 0:
  aggressive_portion = 100
else:
  aggressive_portion = 0


## 종목 출력하기
aggressive_etf_list_text = ''
defensive_etf_list_text = ''

# 카나리아 자산군 중 모멘텀스코어 0 미만 개수: 0
if canary_etf_negative_count == 0:
  momentum_scores_aggressive_top_6 = df_etf_momentum_score[aggressive_etf].transpose().nlargest(6, 'momentum_score').transpose()

  str_aggressive_momentum_score = str_today + str_strategy + "### 공격자산 Momentum Score"
  display(Markdown(str_aggressive_momentum_score))
  display(momentum_scores_aggressive_top_6)
  etf_columns = momentum_scores_aggressive_top_6.columns
  aggressive_etf_list_text = ' '.join([str(asset) for asset in etf_columns])

# 0 미만 카나리아 자산군 개수: 1 이상
if canary_etf_negative_count >= 1:
  ma_12mo_defensive_top_3 = df_etf_12mo_ma.iloc[1:][defensive_etf].transpose().nlargest(3, '12mo_ma_ror(%)').transpose()

  str_defensive_12mo_ma = str_today + str_strategy + "### 안전자산 Momentum Score"
  display(Markdown(str_defensive_12mo_ma))
  display(ma_12mo_defensive_top_3)

  # 안전자산 중 0 이상인 것만 필터링하기
  filtered_index = ma_12mo_defensive_top_3.columns[(ma_12mo_defensive_top_3 < 0).any()]
  df_etf_defensive_positive_index = ma_12mo_defensive_top_3.drop(filtered_index, axis=1).columns
  defensive_etf_list_text = ' '.join([str(asset) for asset in df_etf_defensive_positive_index])

str_canary_text = "## 카나리아 자산군 중 모멘텀스코어 0 미만 개수: " + str(canary_etf_negative_count)
str_aggressive_text = "## 공격자산 비율: " + str(aggressive_portion) + " %"
display(Markdown(str_today[1:] + str_strategy))
display(Markdown(str_canary_text))
display(Markdown(str_aggressive_text))

str_aggressive_etf_list = '## 추천 공격자산: '
if canary_etf_negative_count == 0:
  str_aggressive_etf_list += aggressive_etf_list_text

str_defensive_etf_list = '## 추천 안전자산: '
if canary_etf_negative_count >= 1:
  str_defensive_etf_list += defensive_etf_list_text

str_defensive_etf_count = '## 안전자산 수익률 0 이상 개수'

display(Markdown(str_aggressive_etf_list))
display(Markdown(str_defensive_etf_list))

# 안전자산 개수
str_etf_defensive_positive_index = '## 안전자산 투자 개수: ' + str(len(df_etf_defensive_positive_index))
display(Markdown(str_etf_defensive_positive_index))

# csv에 자산 투자 조언 추가
with open(output_path + filename, 'a') as f:
  f.write('\n')
  f.write(f'{str_today[1:] + str_strategy}\n')
  f.write(f'{str_canary_text}\n')
  f.write(f'{str_aggressive_text}\n')
  f.write(f'{str_aggressive_etf_list}\n')
  f.write(f'{str_defensive_etf_list}\n')
  f.write(f'{str_etf_defensive_positive_index}')

### 2023-08-25 BAA_med ### 안전자산 Momentum Score

                  BIL    DBC     LQD
12mo_ma_ror(%) 2.3108 0.1822 -0.0593

## 2023-08-25 BAA_med

## 카나리아 자산군 중 모멘텀스코어 0 미만 개수: 3

## 공격자산 비율: 0 %

## 추천 공격자산:

## 추천 안전자산: BIL DBC

## 안전자산 투자 개수: 2